### ISSUE TITLE
Samples can be updated leveraging the auto-hydration support in Config Sync

### ISSUE THREAD

**Issue by janetkuo** [GoogleCloudPlatform/anthos-config-management-samples#50]
For example, https://github.com/GoogleCloudPlatform/anthos-config-management-samples/tree/main/multi-cluster-access-and-quota can be updated to render the manifests in the cluster leveraging native support of Kustomize in Config Sync.

**Comment by mathieu-benoit** [comment]
Thanks for bringing this up @janetkuo.

I will start do some research about which sample has this old way to deal with Kustomize with Config Sync and see where it's used or not in docs, etc. From there, we could plan accordingly how/when making the updates.

As an example, this one https://github.com/GoogleCloudPlatform/anthos-config-management-samples/tree/main/kustomize-pipeline is another one in this situation.

**Comment by janetkuo** [comment]
I think it's fine to keep it, as some customers prefer to have things rendered before syncing them to the cluster. For example, we have https://cloud.google.com/anthos-config-management/docs/tutorials/multiple-environments-config-sync that leverages the Kustomize rendering feature and https://cloud.google.com/anthos-config-management/docs/tutorials/multiple-environments-cloud-build that uses Cloud Build to render Kustomize manifests before syncing them to the cluster. 

If keeping both makes the guide too complicated, it's fine to just keep the auto-rendering one for simplicity.

**Comment by Shabirmean** [comment]
@mathieu-benoit - is there an update on this issues?

**Comment by minherz** [comment]
Closing this improvement due to capacity limitations. 
The following up-to-date documentation pages can be used further to implement the built-in rendering functionality of Config Sync:
* https://cloud.google.com/anthos-config-management/docs/tutorials/config-sync-helm
* https://cloud.google.com/anthos-config-management/docs/tutorials/multiple-environments-config-sync
